snippets/statistics-simple-jsf/src/main/java/com/camunda/bpm/demo/statistics/milestone/StatisticsMilestoneBean.java
package com.camunda.bpm.demo.statistics.milestone;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.camunda.bpm.engine.ProcessEngine;
import org.camunda.bpm.engine.history.HistoricActivityInstance;

@SessionScoped
@Named
public class StatisticsMilestoneBean implements Serializable {

  private static final long serialVersionUID = 1L;

  @Inject
  private ProcessEngine engine;

  private List<DataItem> statsMilestones;

  public String getAxisDates() {
    ArrayList<String> names = new ArrayList<String>();
    for (DataItem item : getStats()) {
      names.add(item.getName().replaceAll("\n", " ").replaceAll("\r", ""));
    }
    String result= "[\""+join(names, "\",\"")+"\"]";
    return result;
  }

  public String getChartData() {
    ArrayList<String> values = new ArrayList<String>();
    for (DataItem item : getStats()) {
      values.add(String.valueOf( item.getValue() ));
    }
    String result="["+join(values, ",")+"]";
    return result;
  }

  public void updateStats() {
    statsMilestones = null;
  }

  public List<DataItem> getStats() {
    if (statsMilestones == null) {
      statsMilestones = getMilestoneStatistics();
    }
    return statsMilestones;
  }

  public List<DataItem> getMilestoneStatistics() {
    ArrayList<DataItem> dataItems = new ArrayList<DataItem>();
    DataItem lastDataItem = null;

    List<HistoricActivityInstance> activities = engine.getHistoryService().createHistoricActivityInstanceQuery() //
        .activityType("intermediateNoneThrowEvent")
        .orderByActivityId().asc().list();

    for (HistoricActivityInstance historicActivityInstance : activities) {
      if (lastDataItem == null || !lastDataItem.getId().equals(historicActivityInstance.getActivityId())) {
        lastDataItem = new DataItem();
        lastDataItem.setId(historicActivityInstance.getActivityId());
        lastDataItem.setName(historicActivityInstance.getActivityName());
        lastDataItem.setValue(1);
        dataItems.add(lastDataItem);
      } else {
        lastDataItem.incValue();
      }
    }

    return dataItems;
  }

  static public String join(List<String> list, String conjunction) {
    StringBuilder sb = new StringBuilder();
    boolean first = true;
    for (String item : list) {
      if (first)
        first = false;
      else
        sb.append(conjunction);
      sb.append(item);
    }
    return sb.toString();
  }
}

snippets/statistics-simple-jsf/src/main/java/com/camunda/bpm/demo/statistics/milestone/StatisticsPhasesBean.java
package com.camunda.bpm.demo.statistics.milestone;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.camunda.bpm.engine.ProcessEngine;
import org.camunda.bpm.engine.history.HistoricActivityInstance;

@SessionScoped
@Named
public class StatisticsPhasesBean implements Serializable {

  private static final long serialVersionUID = 1L;

  @Inject
  private ProcessEngine engine;

  private List<DataItem> stats;

  public String getAxisDates() {
    ArrayList<String> names = new ArrayList<String>();
    for (DataItem item : getStats()) {
      names.add(item.getName().replaceAll("\n", " ").replaceAll("\r", ""));
    }
    String result= "[\""+join(names, "\",\"")+"\"]";
    return result;
  }

  public String getChartData() {
    ArrayList<String> values = new ArrayList<String>();
    for (DataItem item : getStats()) {
      values.add(String.valueOf( item.getValue() ));
    }
    String result="["+join(values, ",")+"]";
    return result;
  }

  public void updateStats() {
    stats = null;
  }

  public List<DataItem> getStats() {
    if (stats == null) {
      stats = getPhasesStatistics();
    }
    return stats;
  }

  public List<DataItem> getPhasesStatistics() {
    ArrayList<DataItem> dataItems = new ArrayList<DataItem>();
    DataItem lastDataItem = null;

    List<HistoricActivityInstance> activities = engine.getHistoryService().createHistoricActivityInstanceQuery() //
        .activityType("subProcess")
        .unfinished()
        .orderByActivityId().asc().list();

    for (HistoricActivityInstance historicActivityInstance : activities) {
      if (lastDataItem == null || !lastDataItem.getId().equals(historicActivityInstance.getActivityId())) {
        lastDataItem = new DataItem();
        lastDataItem.setId(historicActivityInstance.getActivityId());
        lastDataItem.setName(historicActivityInstance.getActivityName());
        lastDataItem.setValue(1);
        dataItems.add(lastDataItem);
      } else {
        lastDataItem.incValue();
      }
    }

    return dataItems;
  }

  static public String join(List<String> list, String conjunction) {
    StringBuilder sb = new StringBuilder();
    boolean first = true;
    for (String item : list) {
      if (first)
        first = false;
      else
        sb.append(conjunction);
      sb.append(item);
    }
    return sb.toString();
  }
}

snippets/statistics-simple-jsf/src/main/webapp/stats.xhtml
<!DOCTYPE HTML>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">

  <h:head>
	  <title>Statistics</title>
  		<h:outputStylesheet library="css" name="jquery.jqplot.css"/>
  </h:head>
  <h:body>
	  <div class="container">
	  	<h:form>          
	 		<div id="milestoneChart"></div>
	  		<h:commandButton action="#{statisticsMilestoneBean.updateStats()}" value="Update" styleClass="btn btn-primary"/>
	 		<div id="phasesChart"></div>
	  		<h:commandButton action="#{statisticsPhasesBean.updateStats()}" value="Update" styleClass="btn btn-primary"/>
	  	</h:form>
	  </div>
	  
  	  <h:outputScript library="js" name="jquery.js"  />	  
  	  <h:outputScript library="js" name="jquery.jqplot.js"  />
  	  <h:outputScript library="js" name="jqplot.barRenderer.js"  />
  	  <h:outputScript library="js" name="jqplot.categoryAxisRenderer.js"  />
	  <h:outputScript target="body">
	  
$(document).ready(function(){
		$.jqplot.config.enablePlugins = true;

		var axisDatesMilestone = #{statisticsMilestoneBean.axisDates};
		var chartDataMilestone = #{statisticsMilestoneBean.chartData};
         var milestoneChart = $.jqplot('milestoneChart', [chartDataMilestone], {
            title: 'Reached Milestones (Sum)',
             seriesDefaults:{
                 renderer: $.jqplot.BarRenderer,
                 rendererOptions: {
                    barDirection: 'horizontal'
                }, 
                color: '#610000',
                pointLabels: { show: true }
            },   
            axes: {
                yaxis: {                            
                        renderer:  $.jqplot.CategoryAxisRenderer,
                        ticks: axisDatesMilestone
                },
                xaxis: {
                    tickInterval: 1
                }
            }
        });
            
            
		var axisDatesPhases = #{statisticsPhasesBean.axisDates};
		var chartDataPhases = #{statisticsPhasesBean.chartData};
        var phasesChart = $.jqplot('phasesChart', [chartDataPhases], {
            title: 'Currently Active Phases (Count)',
             seriesDefaults:{
                 renderer: $.jqplot.BarRenderer,
                 rendererOptions: {
                    barDirection: 'horizontal'
                }, 
                color: '#610000',
                pointLabels: { show: true }
            },
            axes: {
                yaxis: {                            
                        renderer:  $.jqplot.CategoryAxisRenderer,
                        ticks: axisDatesPhases
                },
                xaxis: {
                    tickInterval: 1
                }
            }
        });            
});	 	          
	  </h:outputScript>
  </h:body>
</html>