one-time-examples/underwriting/src/main/java/com/camunda/demo/underwriting/domain/Application.java
package com.camunda.demo.underwriting.domain;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class Application {

  private String id;

  private String customerId;
  private String customerName;
  
  private int age;
  private String risk;
  private String type;
  
  private boolean smoker;
  
  public Application() {
    id = UUID.randomUUID().toString();
    id = id.substring(0, 8);
  }

  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public String getCustomerName() {
    return customerName;
  }

  public void setCustomerName(String customerName) {
    this.customerName = customerName;
  }

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public boolean isSmoker() {
    return smoker;
  }

  public void setSmoker(boolean smoker) {
    this.smoker = smoker;
  }

  public int getAge() {
    return age;
  }

  public void setAge(int age) {
    this.age = age;
  }

  public String getRisk() {
    return risk;
  }

  public void setRisk(String risk) {
    this.risk = risk;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

}

one-time-examples/underwriting/src/main/java/com/camunda/demo/underwriting/jsf/CaseController.java
package com.camunda.demo.underwriting.jsf;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import javax.enterprise.context.SessionScoped;
import javax.enterprise.inject.Produces;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.camunda.bpm.engine.ProcessEngine;
import org.camunda.bpm.engine.history.HistoricCaseActivityInstance;
import org.camunda.bpm.engine.impl.cmmn.entity.runtime.CaseExecutionEntity;
import org.camunda.bpm.engine.impl.cmmn.execution.CaseExecutionState;
import org.camunda.bpm.engine.repository.CaseDefinition;
import org.camunda.bpm.engine.runtime.CaseExecution;
import org.camunda.bpm.engine.runtime.CaseInstance;
import org.camunda.bpm.engine.task.Task;
import org.camunda.bpm.model.cmmn.impl.CmmnModelConstants;

import com.camunda.demo.underwriting.Constants;
import com.camunda.demo.underwriting.domain.Application;

@Named
@SessionScoped
public class CaseController implements Serializable {

  private static final long serialVersionUID = 1L;

  private Application application;

  @Inject
  private ProcessEngine engine;
  
  private CaseInstance caseInstance;

  private Task selectedTask;

  private CaseDefinition caseDefinition;

  @Inject
  private UserController currentUser;

  private Map<String, Object> taskFormVariables = new HashMap<String, Object>();

  private String activityForbiddenText;

  private List<CaseExecution> activeCaseExecutions;
  private List<CaseExecution> enabledCaseExecutions;

  private List<HistoricCaseActivityInstance> historicActivityInstances;

  public void initCaseByParameters() {
    // TODO: Make sure it is not executed every time we klick RELOAD!
    Map<String, String> requestParameterMap = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
    String taskId = requestParameterMap.get("taskId");
    String caseInstanceId = requestParameterMap.get("caseInstanceId");
    if (taskId != null) {
      selectTask(taskId);
      if (selectedTask!=null) {
        Task loadedTask = selectedTask;
        initByCaseInstanceId(selectedTask.getCaseInstanceId()); // does a reset!
        selectedTask = loadedTask;
       }
    } else if (caseInstanceId != null) {
      initByCaseInstanceId(caseInstanceId);
    }

  }

  private void reset() {
    selectedTask = null;
    caseInstance = null;
    caseDefinition = null;
    activityForbiddenText = null;
    taskFormVariables = new HashMap<String, Object>();
  }

  public void initByCaseInstanceId(final String caseInstanceId) {
    reset();
    if (engine.getCaseService().createCaseExecutionQuery().caseInstanceId(caseInstanceId).count()==0) {
      return;
    }
    application = (Application) engine.getCaseService().getVariable(caseInstanceId, Constants.VAR_NAME_APPLICATION);
    caseInstance = engine.getCaseService().createCaseInstanceQuery().caseInstanceId(caseInstanceId).singleResult();
    caseDefinition = engine.getRepositoryService().getCaseDefinition(caseInstance.getCaseDefinitionId());
    
    activeCaseExecutions = new ArrayList<CaseExecution>();
    enabledCaseExecutions = new ArrayList<CaseExecution>();
    
    loadCaseInstanceStatus();
  }

  private void loadCaseInstanceStatus() {
    List<CaseExecution> caseExecutions = engine.getCaseService().createCaseExecutionQuery().caseInstanceId(caseInstance.getId()).list();
    for (CaseExecution caseExecution : caseExecutions) {
      if (caseExecution.isActive()) {
        activeCaseExecutions.add(caseExecution);
      }
      else if (caseExecution.isEnabled()) {
        enabledCaseExecutions.add(caseExecution);
      }
    }
    
    historicActivityInstances = engine.getHistoryService().createHistoricCaseActivityInstanceQuery() //
          .caseInstanceId(caseInstance.getId()) //
          .completed() //
          .list();
  }
  
  public Object getTaskVariable(String name) {
    if (selectedTask!=null) {
      return engine.getTaskService().getVariable(selectedTask.getId(), "capableUnderwriters");
    }
    return null;
  }

  public String executeCaseActivityAndSelectTask(CaseExecution execution) {
    engine.getCaseService().manuallyStartCaseExecution(execution.getId());
    
    List<Task> tasks = engine.getTaskService().createTaskQuery().caseExecutionId(execution.getId()).list();
    if (tasks.size() > 0) {
      selectedTask = tasks.get(0);
    }
    
    // now enabled/active activities have changed
    refreshCaseInfo();
    
    // Heuristik: Den letzten Task zum aktuellen Case selektieren - eine
    // Aktivität könnte ja auch
    // ein Prozess sein der keine oder mehrere Aufgaben erzeugt!
//    final List<Task> tasks = engine.getTaskService().createTaskQuery().caseInstanceId(caseInstance.getId()).orderByTaskCreateTime().desc().list();
//    if (tasks.size() > 0) {
//      selectedTask = tasks.get(0);
////      claimSelectedAskForCurrentUser();
//    }
//    refreshCaseInfo();
    return "";
    //return getTaskFormLink(selectedTask.getId());
  }

  public boolean isRunning(String activityId) {
//    for (Task task : caseInstanceInfo.getActiveTasks()) {
//      if (task.getTaskDefinitionKey().equals(activityId)) {
//        return true;
//      }
//    }
//    for (ProcessInstance pi : caseInstanceInfo.getActiveProcesses()) {
//      if (pi.getProcessDefinitionId().equals(activityId)) {
//        return true;
//      }
//    }
    return false;
  }

  public boolean isFinished(String activityId) {
//    for (HistoricTaskInstance task : caseInstanceInfo.getHistoricTasks()) {
//      if (task.getTaskDefinitionKey().equals(activityId)) {
//        return true;
//      }
//    }
//    for (HistoricProcessInstance pi : caseInstanceInfo.getHistoricProcesses()) {
//      if (pi.getProcessDefinitionId().equals(activityId)) {
//        return true;
//      }
//    }
    return false;
  }

  public String getTaskFormLink(CaseExecution caseExecution) {
    if (caseExecution.getActivityType()==CmmnModelConstants.CMMN_ELEMENT_HUMAN_TASK) {
      Task task = engine.getTaskService().createTaskQuery().caseExecutionId(caseExecution.getId()).initializeFormKeys().singleResult();
      return getFormLink(task);
    }
    else return null;
  }
  
  public String getFormLink(Task task) {
    if (task.getCaseInstanceId()==null ){
      // no task from case
      return "/../camunda/app/tasklist/default/#/?task="+task.getId()+"&detailsTab=task-detail-form";
    }
    
    String formKey = task.getFormKey();
    if (formKey == null) {
      return null;
    }    
    return formKey.replaceAll("app:", "") + "?taskId=" + task.getId();    
  }

  public void refreshCaseInfo() {
    initByCaseInstanceId(caseInstance.getId());
  }

  public void deselectTask() {
    selectedTask = null;
  }

  public void selectTask(final String taskId) {
    selectedTask = engine.getTaskService().createTaskQuery().taskId(taskId).singleResult();
    if(selectedTask==null) {
      return;
    }
    claimSelectedTaskForCurrentUser();
  }

  private void claimSelectedTaskForCurrentUser() {
    // unclaim (tink about it - at the moment we need it as otherwise we
    // canno claim something already assigned to somebody else -> exception)
    engine.getTaskService().claim(selectedTask.getId(), null);
    // and claim for me
    engine.getTaskService().claim(selectedTask.getId(), currentUser.getUserId());
  }

  @Produces
  @Named("application")
  public Application getApplicationForSelectedCaseInstance() {
    return application;
  }

  public Map<String, Object> getTaskFormVariables() {
    return taskFormVariables;
  }

  public String completeSelectedTask() {
    
    HashMap<String, Object> variables = saveVariables();
    
    // complete task (variables are ignored due to bug https://app.camunda.com/jira/browse/CAM-3261)
    // hence variables are saved beforehand (workaround)
    engine.getTaskService().complete(selectedTask.getId(), variables);

    // reset task form
    taskFormVariables = new HashMap<String, Object>();
    refreshCaseInfo();
    selectedTask = null;
    if (caseInstance==null) {
      return "case-instances.jsf";      
    } else {
      return "case-form.jsf?caseInstanceId=" + caseInstance.getId();
    }
  }

  private HashMap<String, Object> saveVariables() {
    HashMap<String, Object> variables = new HashMap<String, Object>();
    // workaround to use boolean variables
    for (Entry<String, Object> entry : taskFormVariables.entrySet()) {
      if (entry.getValue()!=null && ("true".equals(entry.getValue()) || "false".equals(entry.getValue()))) {
        variables.put(entry.getKey(), Boolean.valueOf((String)entry.getValue()));        
      }
      else {
        variables.put(entry.getKey(), entry.getValue());
      }
    }
    // save changed to variables object bound to JSF UI
    variables.put(Constants.VAR_NAME_APPLICATION, application);
    
    engine.getCaseService().setVariables(selectedTask.getCaseExecutionId(), variables);
    return variables;
  }

  public void saveSelectedTask() {
    saveVariables();
//    engine.getCaseService().setVariable(selectedTask.getCaseExecutionId(), Constants.VAR_NAME_APPLICATION, application);
//    engine.getCaseService().setVariable(selectedTask.getCaseExecutionId(), Constants.VAR_NAME_EVALUATION_COMMENTS, application);
  }

  public String getProcessDefinitionName(final String processDefinitionId) {
    return engine.getRepositoryService().createProcessDefinitionQuery().processDefinitionId(processDefinitionId).singleResult().getName();
  }

  public CaseInstance getCaseInstance() {
    return caseInstance;
  }

  public Application getApplication() {
    return application;
  }

  public Task getSelectedTask() {
    return selectedTask;
  }

  public CaseDefinition getCaseDefinition() {
    return caseDefinition;
  }

  public String getActivityForbiddenText() {
    return activityForbiddenText;
  }

  ////////////////////////
  

one-time-examples/underwriting/src/main/java/com/camunda/demo/underwriting/jsf/CaseListController.java
package com.camunda.demo.underwriting.jsf;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.inject.Inject;
import javax.inject.Named;

import org.camunda.bpm.engine.ProcessEngine;
import org.camunda.bpm.engine.repository.CaseDefinition;
import org.camunda.bpm.engine.runtime.CaseInstance;

import com.camunda.demo.underwriting.Constants;
import com.camunda.demo.underwriting.domain.Application;

@Named
public class CaseListController implements Serializable {

  private static final long serialVersionUID = 1L;

  @Inject
  private ProcessEngine processEngine;

  @Inject
  @Named
  private CaseController caseController;

  private ArrayList<CaseRow> rows;

  public List<CaseRow> getRunningCases() {
    if (rows == null) {
      rows = new ArrayList<CaseRow>();
      List<CaseInstance> caseInstances = processEngine.getCaseService().createCaseInstanceQuery().active().list();
      for (CaseInstance caseInstance : caseInstances) {
        Application application = (Application) processEngine.getCaseService().getVariable(caseInstance.getId(), Constants.VAR_NAME_APPLICATION);
        CaseDefinition caseDefinition = processEngine.getRepositoryService().getCaseDefinition(caseInstance.getCaseDefinitionId());
        rows.add(new CaseRow(caseInstance, caseDefinition, application));
      }
    }
    return rows;
  }

  public String selectCase(final String caseId) {
    caseController.initByCaseInstanceId(caseId);
    return "case-form";
  }


}

one-time-examples/underwriting/src/main/java/com/camunda/demo/underwriting/jsf/TasklistController.java
package com.camunda.demo.underwriting.jsf;

import java.util.ArrayList;
import java.util.List;

import javax.inject.Inject;
import javax.inject.Named;

import org.camunda.bpm.engine.ProcessEngine;
import org.camunda.bpm.engine.identity.Group;
import org.camunda.bpm.engine.repository.CaseDefinition;
import org.camunda.bpm.engine.runtime.CaseInstance;
import org.camunda.bpm.engine.task.Task;

import com.camunda.demo.underwriting.Constants;
import com.camunda.demo.underwriting.domain.Application;

@Named
public class TasklistController {

  @Inject
  private ProcessEngine processEngine;

  @Inject
  @Named
  private CaseController caseController;

  @Inject
  @Named
  private UserController userController;

  private List<TaskRow> taskRows;

  public List<TaskRow> getAllTasks() {
    // lazy load tasks if not yet done
    if (taskRows == null) {
      taskRows = new ArrayList<TaskRow>();
      // Todo: check that somebody is logged in
      
      List<Task> tasksForUser = processEngine.getTaskService().createTaskQuery() //
          .taskAssignee(userController.getUserId()) //
          .active() //
          .orderByTaskCreateTime().desc() //
          .initializeFormKeys() //
          .list();
      taskRows.addAll(createTaskRows(tasksForUser));

      List<Group> groups = processEngine.getIdentityService().createGroupQuery().groupMember(userController.getUserId()).list();
      List<String> groupIds = new ArrayList<String>();
      for (final Group group : groups) {
        groupIds.add(group.getId());
      }
      if (groupIds.size() > 0) {
        List<Task> tasksForGroups = processEngine.getTaskService().createTaskQuery() //
            .taskCandidateGroupIn(groupIds) //
            .active() //
            .orderByTaskCreateTime().desc() //
            .initializeFormKeys() //
            .list();
        taskRows.addAll(createTaskRows(tasksForGroups));
      }
    }
    return taskRows;
  }

  private List<TaskRow> createTaskRows(final List<Task> tasks) {
    List<TaskRow> taskRows = new ArrayList<TaskRow>();
    for (Task task : tasks) {
      CaseInstance caseInstance = null;
      Application application = null;
      CaseDefinition caseDefinition = null;

      if (task.getCaseInstanceId() != null) {
        caseInstance = processEngine.getCaseService().createCaseInstanceQuery().caseInstanceId(task.getCaseInstanceId()).singleResult();
        caseDefinition = processEngine.getRepositoryService().getCaseDefinition(caseInstance.getCaseDefinitionId());
      }

      application = (Application) processEngine.getTaskService().getVariable(task.getId(), Constants.VAR_NAME_APPLICATION);
      taskRows.add(new TaskRow(task, application, caseInstance, caseDefinition));
    }
    return taskRows;
  }
}

one-time-examples/underwriting/src/main/java/com/camunda/demo/underwriting/jsf/UserController.java
package com.camunda.demo.underwriting.jsf;

import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpSession;
import org.camunda.bpm.engine.ProcessEngine;
import org.camunda.bpm.engine.identity.User;

@SessionScoped
@Named
public class UserController implements Serializable {

  private static final long serialVersionUID = 1L;

  private String userId = "demo";
  private User user;
  private String password;

  @Inject
  private ProcessEngine processEngine;

  public boolean isLoggedIn() {
    return userId != null;
  }

  public String login() {
    user = processEngine.getIdentityService().createUserQuery().userId(userId).singleResult();
    if (user == null) {
      return null;
    }
    return "case-instances";
  }

  public String logout() {
    final Object session = FacesContext.getCurrentInstance().getExternalContext().getSession(false);
    if (session instanceof HttpSession) {
      ((HttpSession) session).invalidate();
    }
    userId = null;
    return "index";
  }

  /**
   * @return the ivUserId
   */
  public String getUserId() {
    return userId;
  }

  /**
   * @param userId
   *          the ivUserId to set
   */
  public void setUserId(final String userId) {
    this.userId = userId;
  }

  /**
   * @return the ivUser
   */
  public User getUser() {
    return user;
  }

  /**
   * @param User
   *          the ivUser to set
   */
  public void setUser(final User user) {
    this.user = user;
  }

  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }
}

one-time-examples/underwriting/src/main/webapp/case-instances.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	template="/WEB-INF/templates/template.xhtml">

	<ui:define name="content">
		<h:head>
			<title>Cases</title>
		</h:head>
		<h:body>
			<div class="page-header">
				<h1>Cases</h1>
			</div>
			<div class="container">
				<div>
					<h3>Active Cases</h3>
					<h:form>
					<h:dataTable
						value="#{caseListController.runningCases}"
						var="currentCaseRow" styleClass="table">
						<h:column>
							<a href="case-form.jsf?caseInstanceId=#{currentCaseRow.caseInstance.id}">#{currentCaseRow.caseDefinition.name}</a>							
						</h:column>
						<h:column>
							#{currentCaseRow.creditApplication.customerId}
						</h:column>
						<h:column>
							#{currentCaseRow.creditApplication.customerName}
						</h:column>
					</h:dataTable>
					</h:form>
				</div>
				
			</div>
				

		</h:body>
	</ui:define>
</ui:composition>

one-time-examples/underwriting/src/main/webapp/form-decide-application.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	template="case-form.xhtml">

	<ui:define name="task">
		<!-- Todo Show Application -->
		<div>
				Customer ID: 
				<h:outputText value="#{caseController.application.customerId}" />
		</div>				
		<div>				
				Customer Name: 
				<h:outputText value="#{caseController.application.customerName}" />
		</div>	
		 			
		<div>				
				Capable Underwriters: 
				<h:outputText value="#{caseController.getTaskVariable('capableUnderwriters')}" />
		</div>
		 		

		<div>				
				<label>Evaluation Comments</label>
		</div>
		<div>
				<h:inputTextarea rows="6" cols="50" value="#{caseController.taskFormVariables['evaluationComments']}" />
		</div>				
		
		<!-- Decide -->
		<div>
		     <label>Approve? </label>
		</div>
		<div>
			<h:selectOneMenu id="approved" value="#{caseController.taskFormVariables['approved']}">
				<f:selectItem itemValue="#{false}" itemLabel="No" />					
				<f:selectItem itemValue="#{true}" itemLabel="Yes" />
			</h:selectOneMenu>
		</div>
	</ui:define>	
</ui:composition>

one-time-examples/underwriting/src/main/webapp/form-missing.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="case-form.xhtml">

	<ui:define name="task">

		sorry - this form was not implemented for this demo...
		
		<br />
		<br />
		
		<h:graphicImage value="resources/img/missing.jpg" />		

	</ui:define>	
</ui:composition>

one-time-examples/underwriting/src/main/webapp/index.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

<h:head>
	<title>camunda BPM</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="shortcut icon" type="image/x-icon"
		href="#{request.contextPath}/resources/favicon.ico" />
	<h:outputStylesheet name="css/bootstrap.css" />
	<h:outputStylesheet name="css/bootstrap-theme.css" />
	<h:outputStylesheet name="css/app.css" />

	<h:outputScript type="text/javascript" library="webjars/jquery/1.9.0"
		name="jquery.js" />
	<h:outputScript type="text/javascript"
		library="webjars/bootstrap/3.0.0/js" name="bootstrap.js" />


</h:head>

<h:body style="padding-top: 60px; padding-bottom: 40px;">
	<div class="container">
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="navbar-header">
				<a class="navbar-brand" href="#">Underwriting Cockpit</a>
			</div>
		</nav>
		<div class="row">
					<h:form class="col-md-4 col-md-offset-4" id="someForm" role="form">
						<h2>Login</h2>
						<div class="form-group">
							<label>Username</label>
							<h:inputText class="form-control" p:placeholder="username"
									value="#{userController.userId}" />
						</div>
						<div class="form-group">
							<label>Password</label>
							<h:inputSecret class="form-control" p:placeholder="password"
									value="#{userController.password}" />
						</div>
						<h:commandButton value="Login" class="btn btn-primary"
									action="#{userController.login}" />						
					</h:form>

		</div>
		<nav class="navbar navbar-default navbar-fixed-bottom"
			role="navigation" id="footer">
			<div class="text-right">
				powered by <a href="http://www.camunda.org">Camunda BPM</a>
			</div>
		</nav>
	</div>

</h:body>
</html>

one-time-examples/underwriting/src/main/webapp/tasklist.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	template="/WEB-INF/templates/template.xhtml">

	<ui:define name="content">
		<h:head>
			<title>Tasks</title>
		</h:head>
		<h:body>
        <!-- see http://datatables.net/examples/advanced_init/language_file.html -->
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$('#taskTableForm\\:taskTable').dataTable( {
            		
            		}
        		});
			});
		</script>
		<!-- "oLanguage": {
						"sProcessing": "Bitte warten...",
						"sLengthMenu": "_MENU_ Einträge anzeigen",
						"sZeroRecords": "Keine Einträge vorhanden.",
						"sInfo": "_START_ bis _END_ von _TOTAL_ Einträgen",
						"sInfoEmpty": "0 bis 0 von 0 Einträgen",
						"sInfoFiltered": "(gefiltert von _MAX_  Einträgen)",
						"sInfoPostFix": "",
						"sSearch": "Filter",
						"sUrl": "",
						"oPaginate": {
							"sFirst":    "Erster",
							"sPrevious": "Zurück",
							"sNext":     "Nächster",
							"sLast":     "Letzter"
						} -->			
			<div class="page-header">
				<h1>All Tasks</h1>
			</div>

			<div class="container">
			
						<h:form id="taskTableForm">
							<h:dataTable value="#{tasklistController.allTasks}" var="row"
								styleClass="table" id="taskTable">
								<h:column>
									<f:facet name="header">Case</f:facet>
									<h:panelGroup rendered="#{row.caseInstance!=null}">
										<a href="case-form.jsf?caseInstanceId=#{row.caseInstance.id}">#{row.caseDefinition.name}</a>							
									</h:panelGroup>
								</h:column>
								<h:column>
									<f:facet name="header">Task</f:facet>
									<a href="#{caseController.getFormLink(row.task)}">#{row.task.name}</a>									
								</h:column>
								<h:column>
									<f:facet name="header">Customer ID</f:facet>
									<h:panelGroup rendered="#{row.application!=null}">		
											#{row.application.customerId}
										</h:panelGroup>
								</h:column>
								<h:column>
									<f:facet name="header">Customer Name</f:facet>
									<h:panelGroup rendered="#{row.application!=null}">		
											#{row.application.customerName}
										</h:panelGroup>
								</h:column>
							</h:dataTable>
						</h:form>
						
			</div>

		</h:body>
	</ui:define>
</ui:composition>